<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>
<?php $option_values=array('A'=>'','B'=>'','C'=>'','D'=>''); $correct_answer=''; foreach($options as $option){$option_values[$option['label']]=$option['option_text']; if(intval($option['is_correct'])===1)$correct_answer=$option['label'];} ?>
<div class="row"><div class="col-sm-12"><div class="panel panel-info">
<div class="panel-heading"><i class="fa fa-pencil"></i>&nbsp;&nbsp;<?php echo get_phrase('Edit Question'); ?><span class="pull-right"><?php echo html_escape($exam['title']); ?></span></div>
<div class="panel-body"><form method="POST" action="<?php echo base_url(); ?>admin/cbt/update_question/<?php echo intval($exam_id); ?>/<?php echo intval($question['id']); ?>">
<div class="form-group"><label><?php echo get_phrase('Question Type'); ?></label><select name="question_type" id="question_type" class="form-control"><option value="mcq" <?php echo $question['question_type']==='mcq'?'selected':''; ?>><?php echo get_phrase('Multiple Choice'); ?></option><option value="fill_blank" <?php echo $question['question_type']==='fill_blank'?'selected':''; ?>><?php echo get_phrase('Fill in the Blank'); ?></option></select></div>
<div class="form-group"><label><?php echo get_phrase('Question'); ?> <span class="text-danger">*</span></label><textarea name="question_text" class="form-control" rows="4" required><?php echo html_escape($question['question_text']); ?></textarea></div>
<div id="mcq-fields"><label><?php echo get_phrase('Options'); ?> <span class="text-danger">*</span></label><?php foreach($option_values as $label=>$value): ?><div class="form-group"><div class="input-group"><span class="input-group-addon"><?php echo $label; ?></span><input type="text" name="option_<?php echo strtolower($label); ?>" class="form-control mcq-required" value="<?php echo html_escape($value); ?>"></div></div><?php endforeach; ?><div class="form-group"><label><?php echo get_phrase('Correct Answer'); ?> <span class="text-danger">*</span></label><select name="correct_answer" class="form-control mcq-required"><option value=""><?php echo get_phrase('Select correct answer'); ?></option><?php foreach(array('A','B','C','D') as $label): ?><option value="<?php echo $label; ?>" <?php echo $correct_answer===$label?'selected':''; ?>><?php echo $label; ?></option><?php endforeach; ?></select></div></div>
<div id="blank-fields"><div class="form-group"><label><?php echo get_phrase('Correct Answer'); ?> <span class="text-danger">*</span></label><input type="text" name="blank_answer" class="form-control blank-required" value="<?php echo html_escape($fill_blank_answer['correct_answer'] ?? ''); ?>"></div></div>
<a href="<?php echo base_url(); ?>admin/cbt/review_publish/<?php echo intval($exam_id); ?>" class="btn btn-default btn-rounded"><i class="fa fa-arrow-left"></i>&nbsp;<?php echo get_phrase('Cancel'); ?></a><button type="submit" class="btn btn-success btn-rounded"><i class="fa fa-floppy-o"></i>&nbsp;<?php echo get_phrase('Save Changes'); ?></button>
</form></div></div></div></div>
<script type="text/javascript">$(function(){function toggleQuestionFields(){var isMcq=$('#question_type').val()==='mcq';$('#mcq-fields').toggle(isMcq).find('.mcq-required').prop('required',isMcq);$('#blank-fields').toggle(!isMcq).find('.blank-required').prop('required',!isMcq);}$('#question_type').on('change',toggleQuestionFields);toggleQuestionFields();});</script>