-- sql code to add the departments 
INSERT INTO department (name, department_code)
VALUES
('School Administration', 'a1b2c3d4e5f6a7b'),
('Academics', '8c9d0e1f2a3b4c5'),
('Departmental Heads', 'd6e7f8a9b0c1d2e'),
('Examinations & Records', 'f3a4b5c6d7e8f9a'),
('Information Technology (ICT)', '0b1c2d3e4f5a6b7'),
('Finance & Accounts', 'c8d9e0f1a2b3c4d'),
('Human Resources', '5e6f7a8b9c0d1e2'),
('Student Affairs', 'f3a4b5c6d7e8f9b'),
('Admissions & Marketing', '1b2c3d4e5f6a7b8'),
('Library', '9c0d1e2f3a4b5c6'),
('Health Services', 'd7e8f9a0b1c2d3e'),
('Transportation', '4f5a6b7c8d9e0f1'),
('Security', 'a2b3c4d5e6f7a8b'),
('Maintenance & Facilities', '9c0d1e2f3a4b5c7'),
('Catering & Kitchen', 'e6f7a8b9c0d1e2f'),
('Housekeeping', '3a4b5c6d7e8f9a0'),
('Sports & Physical Education', 'b1c2d3e4f5a6b7c'),
('Arts & Culture', '8d9e0f1a2b3c4d5');

-- This script inserts all 18 departments in a single bulk INSERT statement with unique 15-character hexadecimal department codes that mimic MD5 hash formatting.

-- Second batch

INSERT INTO designation (name, department_id)
VALUES
('Proprietor / Proprietress', 5),
('School Owner', 5),
('Chairman', 5),
('Director', 5),
('Executive Director', 5),
('Managing Director', 5),
('School Administrator', 5),
('Principal', 5),
('Vice Principal', 5),
('Assistant Principal', 5),
('Head Teacher', 5),
('Deputy Head Teacher', 5),
('Academic Director', 5),
('School Coordinator', 5),
('Campus Coordinator', 5),
('Academic Coordinator', 6),
('Head of Academics', 6),
('Subject Teacher', 6),
('Class Teacher', 6),
('Form Teacher', 6),
('Early Years Teacher', 6),
('Nursery Teacher', 6),
('Primary School Teacher', 6),
('Secondary School Teacher', 6),
('Tutor', 6),
('Instructor', 6),
('Lecturer', 6),
('Teaching Assistant', 6),
('Special Education Teacher', 6),
('Head of Mathematics Department', 7),
('Head of English Department', 7),
('Head of Science Department', 7),
('Head of Arts Department', 7),
('Head of Commercial Department', 7),
('Head of ICT Department', 7),
('Head of Languages Department', 7),
('Examination Officer', 8),
('Exam Coordinator', 8),
('Assessment Officer', 8),
('Records Officer', 8),
('Result Processing Officer', 8),
('Registrar', 8),
('Chief Security Officer', 17),
('Security Supervisor', 17),
('Security Guard', 17),
('Gate Officer', 17),
('Transport Manager', 16),
('Transport Officer', 16),
('School Bus Driver', 16),
('Driver', 16),
('Driver Assistant', 16);